### ISSUE TITLE
Error inserting into Model with trait

### ISSUE THREAD

**Issue by colinbarstow** [cyrildewit/laravel-page-view-counter#17]
When using the package on my Post model, I am getting an error when inserting/creating a post. 
One of the fields i am inserting is 'user_id' it's value is Auth::user()->id. 
I get an error telling me 'user_id' has no default value, not sure how or why this is happening. 
It's not an issue with my Model because if i remove the trait from the model my insert/create works just fine no issues. 

I should also mention this seems to be an issue with the trait and using Auth::user()->id.
If i hard code a value e.g. $user_id = "1"; the insert works.
if i use $user_id = Auth::user()->id; I get the error
Also if i dd(Auth::user()->id) within my create method, I return the correct value.

Issue seems to happen as soon as the create (database action) is hit.

Any help would be very much appreciated.

**Comment by venkatavinash** [comment]
I had the same problem. Please check the previous issue. 
cyrildewit told me not to use Eloquent create. Instead assign every variable and create. It is discussed in length in previous issue under my name.

Thank you

**Comment by cyrildewit** [comment]
Can you show me the code you are using? Is it something like $post = new Post(); $post->title = 'New Rocks Have Been Found On Mars' or something like Post::create(['title' ='New Rocks Have Been Found On Mars']);.

**Comment by colinbarstow** [comment]
Hi, thanks for replying. I've recieved a message from @venkatavinash someone telling me to view the previous issue as they had the same issue. 

And yeah, i was using 

Post::create(['insert' => $insert....]); 
I've changed it to $post = new Post(); ....etc and it is now working.

I've never experienced this issue before, i've just tried doing some research and no one seems to know why it happens, do you have any idea as to what causes it?

**Comment by colinbarstow** [comment]
Thanks for the pointer, so strange, never had this issue before. I really
want to know why it happens.

**Comment by cyrildewit** [comment]
Maybe a little bit late but a while ago @LuisNeighbur created a pull request that probably fixed this issue. I forgot to pass the fillable attributes in the constructor function.
