### ISSUE TITLE
how to use :  retrievePageVisitsFrom

### ISSUE THREAD

**Issue by wdrasel** [cyrildewit/laravel-page-view-counter#19]
don't work .. 
$article->retrievePageVisitsFrom(Carbon::now()->subWeeks(2));

**Comment by cyrildewit** [comment]
Sorry for the late response but I think that I made a mistake in the documentation. Try this out `->retrievePageVisitsCountFrom()`.

**Comment by cyrildewit** [comment]
Did it work?
