### ISSUE TITLE
not work if use Laravel Scout MySQL Driver

### ISSUE THREAD

**Issue by olipiskandar** [cyrildewit/laravel-page-view-counter#22]
I get the error as below when I combine it with Laravel Scout MySQL Driver
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'page_visits' in 'where clause' (SQL: select count(*) as aggregate from `artikels` where (`id` LIKE %a% OR `jenis` LIKE %a% OR `judul` LIKE %a% OR `slug` LIKE %a% OR `thumbnail` LIKE %a% OR `deskripsi` LIKE %a% OR `categories_id` LIKE %a% OR `content` LIKE %a% OR `source` LIKE %a% OR `status` LIKE %a% OR `users_id` LIKE %a% OR `locked` LIKE %a% OR `created_at` LIKE %a% OR `updated_at` LIKE %a% OR `page_visits` LIKE %a% OR `page_visits_24h` LIKE %a% OR `page_visits_7d` LIKE %a% OR `page_visits_14d` LIKE %a% OR `page_visits_formatted` LIKE %a% OR `page_visits_24h_formatted` LIKE %a% OR `page_visits_7d_formatted` LIKE %a% OR `page_visits_14d_formatted` LIKE %a%))`

**Comment by cyrildewit** [comment]
Can you provide the code that makes this error appear?I'm also

**Comment by cyrildewit** [comment]
Could you provide the code that makes this error appear?

Can  you create a getXxxxAttribute in one of your models and append it. Also comment out or remove everthing of this package from that model. If this error still appears, then it's something else.

-----------------------------
I'm also working on a new version that doesn't appends all those attributes to your models. In the new version it will only add some methods to your model that you can call. This gives you the option if you wan't to append it. It's kinda messy to have 14 attributes 🤔.

**Comment by olipiskandar** [comment]
at last..
migrate to algolia. 
everything works
