### ISSUE TITLE
visitable_id issue

### ISSUE THREAD

**Issue by usman22** [cyrildewit/laravel-page-view-counter#34]
- Laravel Page View Counter Version: #.#.#
- Laravel Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I dont know What visitable_id is
 Integrity constraint violation: 1048 Column 'visitable_id' cannot be null (SQL: insert into `page-views` (`visitable_id`, `visitable_type`, `ip_address`, `updated_at`, `created_at`) values (, App\Doctor, 139.190.64.77, 2018-01-11 09:01:32, 2018-01-11 09:01:32))
see here in the query above, it is taking visitable_id as empty value
please tell me what the issue is

**Comment by cyrildewit** [comment]
See #35
