### ISSUE TITLE
visitable_id issue

### ISSUE THREAD

**Issue by usman22** [cyrildewit/laravel-page-view-counter#35]
- Laravel Page View Counter Version: ^1.0
- Laravel Version: 5.5
- PHP Version: 7.0.0
- Database Driver & Version:

### Description:
I dont know What visitable_id is
Integrity constraint violation: 1048 Column 'visitable_id' cannot be null (SQL: insert into page-views (visitable_id, visitable_type, ip_address, updated_at, created_at) values (, App\Doctor, 139.190.64.77, 2018-01-11 09:01:32, 2018-01-11 09:01:32))
see here in the query above, it is taking visitable_id as empty value
please tell me what the issue is

**Comment by cyrildewit** [comment]
Could you tell me which version you are using of this package?

**Comment by usman22** [comment]
php": ">=7.0.0",
"cyrildewit/laravel-page-view-counter": "^1.0",
and Laravel 5.5

**Comment by cyrildewit** [comment]
I think it's because your composer updated the package to `v.1.x.x`, while it wasn't backwards compatible.

_Did the error appear after updating the composer package? Or did this happen on a fresh install?
Does your doctors table contains an 'id' attribute? (just to be sure)_

Before trying all kind of stuff, try to update the package to the latest release.
Replace `^1.0` in your composer.json file to `"cyrildewit/laravel-page-view-counter": "1.*"`.
Then run `composer update` and check if it got fixed.

If not, publish the migration file for the `page-views` table again and check if they are different. If so, you have to update the `page-views` table schema.

If you're on development, you can simply remove the old migration file and run every migration again. Tell me if you're on production, so I can create a migration for changing the table.

**Comment by usman22** [comment]
my doctor table doesn't have 'id' attribute, i always make primary key of every table by prefixing its table  name like doctor_id etc

**Comment by cyrildewit** [comment]
So this `$doctor->id` does not work, but `$doctor->doctor_id` does work Mmm, I think that I know why you are getting this error.

**Comment by cyrildewit** [comment]
Could you try `$doctor->getKey()` and tell me if that works?

**Comment by usman22** [comment]
ok let me try it

**Comment by usman22** [comment]
add protected $primaryKey = 'doctor_id'; to your Doctor model and try it again.
**this is already done**

**Comment by usman22** [comment]
**$doctor->getKey()** returned me nothing

**Comment by usman22** [comment]
I have updated version as well, still same error

**Comment by usman22** [comment]
what **visitable_id** actually is?

**Comment by cyrildewit** [comment]
> $doctor->getKey() returned me nothing

Weird. It should return the primary key.

**Comment by cyrildewit** [comment]
> what visitable_id actually is?

All the page views are stored in one table (`page-views`) using the [Polymorphic Relationship](https://laravel.com/docs/5.5/eloquent-relationships#polymorphic-relations).

In this table, the `visitable_id` attribute contains the primary key of the model (visitable_type). In this case it would be `App\Doctor`.

**Comment by usman22** [comment]
This is how I'm testing and screen is just blank when i test it
`$doctor = new Doctor;
echo $doctor->getKey();`

**Comment by cyrildewit** [comment]
That's not good! Right now, you're only creating an instance of the Doctor class. But we want to have a record with data.

```php
$doctor = Doctor::find(1); // any number
$doctor->getKey();
```


```php
$doctor = Doctor::find(1); echo $doctor->getKey();
```

->getKey() will use the key name in your model `$primaryKey` to retrieve the primary key value.

**Comment by usman22** [comment]
Issue Solved

**Comment by usman22** [comment]
please tell me one more thing that my project is very big, can I use it for big project?, will it not be slow?

**Comment by cyrildewit** [comment]
Well, I'm not sure. I haven't tested it actually. I'm currently working on v2. It contains some huge improvements and I'm trying to make it so fast as possible. Check out the v2 branch code.

Counting of the total page views is done by the aggrate methods. This is really fast according to some posts. But the counting of unique page views is done by retrieving all the items and then count them. This can be pretty slow if the model has a lot of views.

I will add this kind of information to v2 as sperate section.

**Comment by cyrildewit** [comment]
Have you upated the package and tested it again? (v1.0.3)

**Comment by usman22** [comment]
yes I updated and tested, everything is running fine
but I'm confused that on every page load there is a new entry in database for that model and it will result in taking much space for database table in future.
and i have to use unique page views (and almost all websites use this technique to get just unique reviews), so according to your statement it will be slow to get unique reviews, please do something for its speed and let me know, I have to use it in very big project

**Comment by cyrildewit** [comment]
What are your thoughts? How would you add page view functionality to your models without using this package?

I have got some ideas to make it faster, but I don't know if they are all good enough.

* Caching all the page views and use them to count (can by quite slow if there are 2 million views)
* Caching the page view count only
* Storing the page view count for various periods (configured in the config file or per model) in a table collumn that will be updated every <period> with an artisan command. 

Adding an option in the config to let people decide what they want to use.
1. Store page views by incrementing (or also keep track of the history)
2. Store page views with history only

I create an issue for this topic to keep it organised. Check #36.
