### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by usman22** [cyrildewit/laravel-page-view-counter#38]
- Laravel Page View Counter Version: 1.0.3
- Laravel Version: 5.5
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I need to know how can I use this package for API as well.
Because there are web services in my project and they are also showing total views for each item and I have to store views from that service as well.
can I use this package for storing and retrieving page views as well for JSON response?

**Comment by cyrildewit** [comment]
Yes of course. This package adds the functionality to store and retrieve page views. It doesn't matter how you are using these methods. You can even use ->addPageView() in Events and Commands. 

When a Doctor is retrieved to show it, I call `->addPageView()` and choose one of the count methods to add the total page views as data.

**Comment by usman22** [comment]
sounds good
