### ISSUE TITLE
Counter is no longer working?

### ISSUE THREAD

**Issue by iiCe89** [cyrildewit/laravel-page-view-counter#43]
Counter is no longer working? i have had no problems until the past couple of days when the view count wont exceed 1 ?

**Comment by cyrildewit** [comment]
Could you provide some more information?  Laravel version, package version, stack trace etc.

Did this happen when updating the package?

**Comment by iiCe89** [comment]
hey ! yeh Laravel 5.5 , package version ^1.0 and i believe when running composer update is when the issue occured

**Comment by cyrildewit** [comment]
Are you using `$model->addPageView();` somewhere in the controller to increment the page views?

Have you checked the database table if the views are getting stored? It's probably the 'page-views' table.

**Comment by iiCe89** [comment]
i have `$tutorial->addPageViews();` in controller 
but looks like its no longer inserting IP address in DB

**Comment by cyrildewit** [comment]
When running `composer show -i` you can see all installed versions. Which one are you seeing at this package? v1.0.3 or v1.0.4

**Comment by cyrildewit** [comment]
This is also wrong: `$tutorial->addPageViews();`. It should be `$tutorial->addPageView()`.

**Comment by iiCe89** [comment]
v1.0.3

**Comment by cyrildewit** [comment]
> "but looks like its no longer inserting IP address in DB"

This issue got fixed in v1.0.4 (#39)

**Comment by iiCe89** [comment]
ok cool

**Comment by cyrildewit** [comment]
Try to update the package to v1.0.4 and check again! Thanks

**Comment by iiCe89** [comment]
All working thanks

**Comment by cyrildewit** [comment]
Nice! Glad I could help!
