### ISSUE TITLE
[Feature Request] total number of pageviews for a model

### ISSUE THREAD

**Issue by VincentVanWijk** [cyrildewit/laravel-page-view-counter#52]
Is it possible that you can add a method like Article::getTotalViews(), that adds the views of all the articles together.
for example, i have a site that has a section with news-items, blog-posts, scheduled-events, it would be nice to see wich section of my site attracts the most pageviews.
I know i can het the total myself by looping through all the articles, but it would be nice to have a built-in method for it.

**Comment by cyrildewit** [comment]
Something like the following (but then better)?

**Maybe a `Viewable` facade...**

```php
Viewable::getViewsCountByType(Article::class); // counts all the views with the type App\Models\Article
Viewable::getViewsCountByTypes([Article::class, NewsItem::class, Event::]); // counts all the views with the type App\Models\Article, App\Models\NewsItem, App\Models\Event etc.
```

**Output**
```php
=> 203020
```
```php
[
    'App\Models\Article' => 80201, // total views of all articles
    'App\Models\NewsItem' => 33020, // total views of all news items
    'App\Models\Post' => 500020, // total views of all posts
] // not ordered
```

What code are you using for now?

**Comment by VincentVanWijk** [comment]
yes exactly like that!

i havent't implemented anything yet, but i think I would do something like:
```
$articles = Articles::all();
$total = 0;
foreach($articles as $item)
{
$total += $item->getPageViews();
}
```

**Comment by cyrildewit** [comment]
I think that this also works:

```php
use Cyrildewit\PageViewCounter\Models\PageView;

$articlesViews = PageView::where('visitable_type', Article::class)->count();
```

**Comment by VincentVanWijk** [comment]
ah yes thanks, that looks much cleaner!

**Comment by cyrildewit** [comment]
It's also much faster because calling `Article::all()` will retrieve every article and then it will retrieve all the views of each article with a seperate query.

`PageView::where('visitable_type', Article::class)->count();` will use SQL to filter all views by type and then count them.

**Comment by cyrildewit** [comment]
@VincentVanWijk Quick update! I added a helper to the `2.0` branch. You can use it when it's released.

**Example usage:**

```php
use App\Models\Post;
use App\Models\Hotel;
use App\Models\Location;
use CyrildeWit\EloquentViewable\Support\ViewsHelper;

app(ViewsHelper::class)->getViewsCountByType(Post::class);
app(ViewsHelper::class)->getViewsCountByTypes([Post::class, Hotel::class, Location:class]);

// or if I change it to a facade in the meantime

use ViewsHelper; // ....

ViewsHelper::getViewsCountByType(Post::class);
ViewsHelper::getViewsCountByTypes([Post::class, Hotel::class, Location:class]);
```

I'm not really happy with the name `ViewsHelper`, but I couldn't find anything better at the moment. I thought something like `Viewable`, `ViewsAnalytics` and `ViewableHelper`, but these names are not presenting what the class does. Maybe `ViewTracker` 😄.
