### ISSUE TITLE
unable to use page_views attribute

### ISSUE THREAD

**Issue by DexHunter** [cyrildewit/laravel-page-view-counter#68]
- Laravel Page View Counter Version: 1.0
- Laravel Version: 5.6
- PHP Version: 7.2.2
- Database Driver & Version: mysql

### Description:

Hi, first thank you for sharing this awesome package!

I tried to sort my model (`Activity`) by `page_views` by getting this error:
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function addPageViewThatExpiresAt() on null
```

### Steps To Reproduce:

```
    public function sortByPageView()
    {
        // $acts = Activity::all()->sortByDesc(function ($act){
        //     return $act->getPageViews();
        // });
        $acts = Activity::all()->sortBy('page_views');

        return view('activities.index')->with('activities', $acts);
    }
```

And the `addPageViewThatExpiresAt()` is called at

```
    public function show($id)
    {
        $act = Activity::find($id);
        $act->addPageViewThatExpiresAt(Carbon::now()->addHours(2));
        return view('activities.show')->with('act', $act);
    }
```

edit: The `show` function works without any problem, but I cannot sort by the `page_views`.

And I have did  at `Activity`

```
    use HasPageViewCounter;

    protected $appends = ['page_views'];

    public function getPageViewsAttribute()
    {
        return $this->getPageViews();
    }
```

Any helps? Thank you!

**Comment by cyrildewit** [comment]
Hi, thank thank you for using this package!

Which error do you get when calling `sortByPageView`? Or if there aren't errors, could you post a screenshot of your view?

**Comment by DexHunter** [comment]
Thank you for reply. Here is the error I got
![capture](https://user-images.githubusercontent.com/6930518/40291435-a3350bd8-5cf7-11e8-8d2a-f49a356d8540.PNG)

**Comment by DexHunter** [comment]
> I think you're trying to view an act that doesn't exists. I installed your application and it is working properly .

The viewing of the property actually works, but I still cannot sort by the views. If I use `Activity::orderBy('page_views', 'desc')` I got column does not exist error, if I use `sortByDesc(function ($act) {return $act->getPageViews();)` I got `Method Illuminate\Database\Eloquent\Collection::links does not exist. ` even though I have set `{{$acts->links}}`.  I am pretty stuck at this point.

**Comment by cyrildewit** [comment]
`Activity::orderBy('page_views', 'desc')` will no work, because the `page_view` attribute doesn't exists in the database. It's a magic attribute.

`sortByDesc(function ($act) {return $act->getPageViews();)` works. You're getting this error because your view expects an paginated collection, but since you haven't paginated the acts, the `links()` method will not exists.

The only solution for this is to use a left join. @zymawy already reported this problem at #65. Take a look at my answer over there.

**Comment by DexHunter** [comment]
> The only solution for this is to use a left join

So the `leftJoin` is applied at the `ViewableService`. I wonder how do I perform `leftJoin` on my `Activity` model? 


I don't quite understand what should be the `$query` on https://github.com/cyrildewit/laravel-page-view-counter/blob/2.0/src/ViewableService.php#L243 I tried this on tinker but it does not work:

```
$query = App\Activity::orderBy('created_at', 'desc'); \\ I also tried $query = Activity::find(1) not work neither
$model = app(App\Activity::class);
$query->leftJoin($model->getTable(), "{$model->getTable()}.viewable_id", '=', "{$query->getModel()->getTable()}.id")->orderBy('page_views')->paginate(1);
```

**Comment by cyrildewit** [comment]
@DexHunter to solve your issue, copy paste the following scope to your `Activity` model.

```php
/**
 * Retrieve records sorted by views count.
 *
 * @param  \Illuminate\Database\Eloquent\Builder  $query
 * @param  string  $direction
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function scopeOrderByViewsCount(Builder $query, string $direction = 'desc'): Builder
{
    $viewable = $query->getModel();
    $viewModel = app(\CyrildeWit\PageViewCounter\Contracts\PageView::class);

    return $query->leftJoin($viewModel->getTable(), "{$viewModel->getTable()}.visitable_id", '=', "{$viewable->getTable()}.{$viewable->getKeyName()}")
        ->selectRaw("{$viewable->getTable()}.*, count(`{$viewModel->getTable()}`.{$viewModel->getKeyName()}) as numOfViews")
        ->groupBy("{$viewable->getTable()}.{$viewable->getKeyName()}")
        ->orderBy('numOfViews', $direction);
}
```

You can now do the following:

```php
Activity::orderBy('created_at', 'desc')->orderByViewsCount()->get();
Activity::orderByViewsCount()->paginate();
// etc.
```

To sort in ascending order:

```php
::orderByViewsCount('asc')
```

**Comment by DexHunter** [comment]
Thank you, I think I almost got there however I still got an error:
![
bug1](https://user-images.githubusercontent.com/6930518/40469428-21d05d7c-5f63-11e8-9661-01c1e21745cb.PNG)

I think the problem is that it's selecting `glueapp.activities` instead of `activities` (`glueapp` is the database name I used), but I am not sure how to solve it yet. I'll update if I found a solution.

**Comment by cyrildewit** [comment]
Could you post the code, so I can reproduce this? I only need the `Activity::...->orderByViewsCount().....->pagiante()....`.

**Comment by DexHunter** [comment]
I actually just used the `Activity::orderBy('created_at', 'desc')->orderByViewsCount()->get();` 

The `ActivityController` is [there](https://github.com/DexHunter/cse208-webapp/blob/master/app/Http/Controllers/ActivityController.php#L33) if it would help

**Comment by cyrildewit** [comment]
https://stackoverflow.com/questions/40917189/laravel-syntax-error-or-access-violation-1055-error

**Comment by DexHunter** [comment]
After changing the configuration, it can work but not giving the right results (after I deleted `{{activities->link()}}` at the blade`. It was still sorted by the `created_at` instead of `numOfViews`

**Comment by cyrildewit** [comment]
Try this:

```php
Activity::orderByViewsCount()->orderBy('created_at', 'desc')->get();
```

**Comment by DexHunter** [comment]
This solves my problem. Many thanks!
